### ISSUE TITLE
error bg

### ISSUE THREAD

**Issue by thoriqazzikraa** [Aromakelapa/igdown#1]
error

**Comment by Aromakelapa** [comment]
iya cuy, nnti dibnerin.. lgi sibuk bikin submission

**Comment by Aromakelapa** [comment]
> error

@thoriqazzikraa udah dibenerin cuy, dicoba, gw close ya issue nya

**Comment by thoriqazzikraa** [comment]
> > error
> 
> @thoriqazzikraa udah dibenerin cuy, dicoba, gw close ya issue nya

![Screenshot_2023-05-08-14-33-55-47_375f2148cf8fa4d7b3a7c6a3ff0c7e6c](https://user-images.githubusercontent.com/89589243/236764391-a773b1bb-715c-4ffc-825c-65d8c576f8db.jpg)

ini apa bg?:v
